# main Fastly Terraform configuration
provider "fastly" {
  api_key = var.fastly_api_token
}

resource "fastly_service_vcl" "site" {
  name = var.service_name

  backend {
    name    = "s3_origin"
    address = var.origin_hostname
    port    = 80

    override_host = var.origin_hostname
    use_ssl       = false
    max_conn      = 200
  }

  gzip {
    name = "Generated by default compression policy"
    content_types = [
      "application/x-javascript",
      "application/javascript",
      "application/vnd.ms-fontobject",
      "application/x-font-opentype",
      "application/x-font-truetype",
      "application/x-font-ttf",
      "font/eot",
      "font/opentype",
      "font/otf",
      "image/svg+xml",
      "image/vnd.microsoft.icon",
      "/text/[^/]+/",
      "/application/(?:[^/]+\\+)?(?:json|xml|jwt)/",
    ]
    extensions = [
      "css",
      "js",
      "html",
      "eot",
      "ico",
      "otf",
      "ttf",
      "json",
      "svg",
      "jsonp",
      "txt",
      "vtt",
    ]
  }

  header {
    name       = "Generated by force TLS and enable HSTS"
    action     = "set"
    destination = "http.Strict-Transport-Security"
    source     = "\"max-age=300\""
    type       = "response"
    priority   = 100
  }

  request_setting {
    name             = "Generated by force TLS and enable HSTS"
    force_ssl        = true
    max_stale_age    = 0
    bypass_busy_wait = false
    timer_support    = false
    force_miss       = false
  }

  force_destroy = true

  snippet {
    name     = "redirect_apex_to_www"
    type     = "recv"
    priority = 100
    content  = <<-EOT
      if (req.http.host == "${var.apex_domain}") {
        error 801;
      }
    EOT
  }

  snippet {
    name     = "redirect_apex_to_www_handler"
    type     = "error"
    priority = 100
    content  = <<-EOT
      if (obj.status == 801) {
        set obj.status = 301;
        set obj.http.Location = "https://${var.domain_name}" + req.url;
        return (deliver);
      }
    EOT
  }

  snippet {
    name     = "cache_static_assets"
    type     = "recv"
    priority = 200
    content  = <<-EOT
      if (req.url.ext ~ "^(css|js|png|jpg|jpeg|gif|svg|ico|webp|avif|woff|woff2|json)$" || req.url.path ~ "^/assets/") {
        unset req.http.Cookie;
        set req.grace = 1h;
      }

      if (req.url.path == "/" || req.url.ext == "") {
        unset req.http.Cookie;
        set req.grace = 1h;
      }
    EOT
  }

  snippet {
    name     = "cache_ttl_for_static_content"
    type     = "fetch"
    priority = 200
    content  = <<-EOT
      if (bereq.url.ext ~ "^(css|js|png|jpg|jpeg|gif|svg|ico|webp|avif|woff|woff2|json)$" || bereq.url.path ~ "^/assets/" || bereq.url.path == "/") {
        set beresp.ttl = 1h;
        set beresp.stale_while_revalidate = 60s;
      }
    EOT
  }

  snippet {
    name     = "cache_headers"
    type     = "deliver"
    priority = 200
    content  = <<-EOT
      if (resp.http.Content-Type ~ "^(text/html|text/css|application/javascript|application/json|image/.*)$") {
        set resp.http.Cache-Control = "public, max-age=3600, s-maxage=3600";
      }
      if (obj.hits > 0) {
        set resp.http.X-Cache = "HIT";
      } else {
        set resp.http.X-Cache = "MISS";
      }
    EOT
  }
}

resource "fastly_domain" "www" {
  fqdn      = var.domain_name
  service_id = fastly_service_vcl.site.id
}

resource "fastly_domain" "apex" {
  fqdn      = var.apex_domain
  service_id = fastly_service_vcl.site.id
}

resource "fastly_tls_subscription" "www" {
  certificate_authority = "certainly"
  domains               = [var.domain_name]

  depends_on = [fastly_domain.www]
}
