# main Fastly Terraform configuration
provider "fastly" {
  api_key = var.fastly_api_token
}

resource "fastly_service_vcl" "site" {
  name = var.service_name

  backend {
    name    = "s3_origin"
    address = var.origin_hostname
    port    = 80

    override_host = var.origin_hostname
    use_ssl       = false
    max_conn      = 200
  }

  gzip {
    name = "Generated by default compression policy"
    content_types = [
      "application/x-javascript",
      "application/javascript",
      "application/vnd.ms-fontobject",
      "application/x-font-opentype",
      "application/x-font-truetype",
      "application/x-font-ttf",
      "font/eot",
      "font/opentype",
      "font/otf",
      "image/svg+xml",
      "image/vnd.microsoft.icon",
      "/text/[^/]+/",
      "/application/(?:[^/]+\\+)?(?:json|xml|jwt)/",
    ]
    extensions = [
      "css",
      "js",
      "html",
      "eot",
      "ico",
      "otf",
      "ttf",
      "json",
      "svg",
      "jsonp",
      "txt",
      "vtt",
    ]
  }

  header {
    name        = "Generated by force TLS and enable HSTS"
    action      = "set"
    destination = "http.Strict-Transport-Security"
    source      = "\"max-age=300\""
    type        = "response"
    priority    = 100
  }

  request_setting {
    name             = "Generated by force TLS and enable HSTS"
    force_ssl        = true
    max_stale_age    = 0
    bypass_busy_wait = false
    timer_support    = false
    force_miss       = false
  }

  force_destroy = true

  vcl {
    name = "main"
    content = templatefile("${path.module}/vcl/main.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
    main = true
  }

  vcl {
    name = "redirects"
    content = templatefile("${path.module}/vcl/redirects.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
  }

  vcl {
    name = "static_cache"
    content = templatefile("${path.module}/vcl/static_cache.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
  }

  logging_newrelic {
    name           = "newrelic-logs"
    token          = var.newrelic_insert_key
    region         = var.newrelic_region
    format_version = 2

    format = <<-EOF
      {
        "timestamp": %%{time.start.msec}V,
        "cache_status": "%%{regsub(fastly_info.state, \"^(HIT-(SYNTH)|(HITPASS|HIT|MISS|PASS|ERROR|PIPE)).*\", \"\\\\2\\\\3\")}V",
        "client_ip": "%%h",
        "client_device_type": "%%{client.platform.hwtype}V",
        "client_os_name": "%%{client.os.name}V",
        "client_os_version": "%%{client.os.version}V",
        "client_browser_name": "%%{client.browser.name}V",
        "client_browser_version": "%%{client.browser.version}V",
        "client_as_name": "%%{client.as.name}V",
        "client_as_number": "%%{client.as.number}V",
        "client_connection_speed": "%%{client.geo.conn_speed}V",
        "client_port": %%{client.port}V,
        "client_rate_bps": %%{client.socket.tcpi_delivery_rate}V,
        "client_recv_bytes": %%{client.socket.tcpi_bytes_received}V,
        "client_requests_count": %%{client.requests}V,
        "client_resp_body_size_write": %%{resp.body_bytes_written}V,
        "client_resp_header_size_write": %%{resp.header_bytes_written}V,
        "client_resp_ttfb": %%{time.to_first_byte}V,
        "client_rtt_us": %%{client.socket.tcpi_rtt}V,
        "content_type": "%%{Content-Type}o",
        "domain": "%%{Fastly-Orig-Host}i",
        "fastly_datacenter": "%%{server.datacenter}V",
        "fastly_host": "%%{server.hostname}V",
        "fastly_is_edge": %%{if(fastly.ff.visits_this_service == 0, \"true\", \"false\")}V,
        "fastly_region": "%%{server.region}V",
        "fastly_server": "%%{json.escape(server.identity)}V",
        "host": "%%v",
        "origin_host": "%%v",
        "origin_name": "%%{req.backend.name}V",
        "request": "%%{req.request}V",
        "request_method": "%%m",
        "request_accept_charset": "%%{json.escape(req.http.Accept-Charset)}V",
        "request_accept_language": "%%{json.escape(req.http.Accept-Language)}V",
        "request_referer": "%%{json.escape(req.http.Referer)}V",
        "request_user_agent": "%%{json.escape(req.http.User-Agent)}V",
        "resp_status": "%%s",
        "response": "%%{resp.response}V",
        "service_id": "%%{req.service_id}V",
        "service_version": "%%{req.vcl.version}V",
        "status": "%%s",
        "time_start": "%%{begin:%Y-%m-%dT%H:%M:%SZ}t",
        "time_end": "%%{end:%Y-%m-%dT%H:%M:%SZ}t",
        "time_elapsed": %%D,
        "tls_cipher": "%%{json.escape(tls.client.cipher)}V",
        "tls_version": "%%{json.escape(tls.client.protocol)}V",
        "url": "%%{json.escape(req.url)}V",
        "user_agent": "%%{json.escape(req.http.User-Agent)}V",
        "user_city": "%%{client.geo.city.utf8}V",
        "user_country_code": "%%{client.geo.country_code}V",
        "user_continent_code": "%%{client.geo.continent_code}V",
        "user_region": "%%{client.geo.region}V"
      }
    EOF
  }
}

resource "fastly_domain" "www" {
  fqdn       = var.domain_name
  service_id = fastly_service_vcl.site.id
}

resource "fastly_domain" "apex" {
  fqdn       = var.apex_domain
  service_id = fastly_service_vcl.site.id
}

resource "fastly_tls_subscription" "www" {
  certificate_authority = "certainly"
  domains               = [var.domain_name]

  depends_on = [fastly_domain.www]
}

resource "fastly_tls_subscription" "apex" {
  certificate_authority = "certainly"
  domains               = [var.apex_domain]

  depends_on = [fastly_domain.apex]
}
