# main Fastly Terraform configuration
provider "fastly" {
  api_key = var.fastly_api_token
}

resource "fastly_service_vcl" "site" {
  name = var.service_name

  backend {
    name    = "s3_origin"
    address = var.origin_hostname
    port    = 80

    override_host = var.origin_hostname
    use_ssl       = false
    max_conn      = 200
  }

  gzip {
    name = "Generated by default compression policy"
    content_types = [
      "application/x-javascript",
      "application/javascript",
      "application/vnd.ms-fontobject",
      "application/x-font-opentype",
      "application/x-font-truetype",
      "application/x-font-ttf",
      "font/eot",
      "font/opentype",
      "font/otf",
      "image/svg+xml",
      "image/vnd.microsoft.icon",
      "/text/[^/]+/",
      "/application/(?:[^/]+\\+)?(?:json|xml|jwt)/",
    ]
    extensions = [
      "css",
      "js",
      "html",
      "eot",
      "ico",
      "otf",
      "ttf",
      "json",
      "svg",
      "jsonp",
      "txt",
      "vtt",
    ]
  }

  header {
    name        = "Generated by force TLS and enable HSTS"
    action      = "set"
    destination = "http.Strict-Transport-Security"
    source      = "\"max-age=300\""
    type        = "response"
    priority    = 100
  }

  request_setting {
    name             = "Generated by force TLS and enable HSTS"
    force_ssl        = true
    max_stale_age    = 0
    bypass_busy_wait = false
    timer_support    = false
    force_miss       = false
  }

  force_destroy = true

  vcl {
    name = "main"
    content = templatefile("${path.module}/vcl/main.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
    main = true
  }

  vcl {
    name = "redirects"
    content = templatefile("${path.module}/vcl/redirects.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
  }

  vcl {
    name = "static_cache"
    content = templatefile("${path.module}/vcl/static_cache.vcl", {
      domain_name = var.domain_name
      apex_domain = var.apex_domain
    })
  }
}

resource "fastly_domain" "www" {
  fqdn       = var.domain_name
  service_id = fastly_service_vcl.site.id
}

resource "fastly_domain" "apex" {
  fqdn       = var.apex_domain
  service_id = fastly_service_vcl.site.id
}

resource "fastly_tls_subscription" "www" {
  certificate_authority = "certainly"
  domains               = [var.domain_name]

  depends_on = [fastly_domain.www]
}

resource "fastly_tls_subscription" "apex" {
  certificate_authority = "certainly"
  domains               = [var.apex_domain]

  depends_on = [fastly_domain.apex]
}
